### PR TITLE
Added support for @generated marker

### PR DESCRIPTION
**Pull request by anriha**
This PR adds support for @generated marker as specified at https://generated.at/ This marks generated code as such and allows it to be skipped in CI/CD. I am just not sure if this is the right format or if adding it after current message would be better.

### CODE REVIEW

**Comment by Gobot1234** [comment]
I think sticking to the same format as protoc might be a good idea, the `# @generated` part doesn't have to be on the first line does it? Could it be moved to below the plugin line?

**Review by Gobot1234 — DISMISSED** [review]

**Comment by anriha** [comment]
Yes you are probably right, it seems that it just has to be somewhere at the beginning (not clearly defined). But from examples I found it seems that it can be below.

**Review by Gobot1234 — DISMISSED** [review]

**Comment by Gobot1234** [comment]
One more idea would be to regenerate the pre-compiled files in lib/google/protobuf

**Comment by anriha** [comment]
I regenerated all the lib/google/protobuf files. Looking at the output it seems like the generated files had wrong documentation for attributes (before attribute definition, not after). So this also fixes that.

**Comment by Gobot1234** [comment]
Thanks, this looks great

**Review by Gobot1234 — APPROVED** [review]

**Pull request merged**
