### PR TITLE
Bug fix in casing.sanitize_name for names starting with an int

### PR DESCRIPTION
**Pull request by Gobot1234**

### CODE REVIEW

**Comment by nat-n** [comment]
Nice catch. Would be good to have a test for this.

**Comment by Gobot1234** [comment]
Only found this due to #187 and code using an int would be invalid
```proto
message Test {
    bool value = 1;
    string 23 = 2;
}
```

**Comment by nat-n** [comment]
> Only found this due to #187 and code using an int would be invalid
> 
> ```protobuf
> message Test {
>     bool value = 1;
>     string 23 = 2;
> }
> ```

Do you mean that there isn't actually a real scenario that would trigger the bug caused here?

**Comment by Gobot1234** [comment]
It

> > Only found this due to #187 and code using an int would be invalid
> > ```protobuf
> > message Test {
> >     bool value = 1;
> >     string 23 = 2;
> > }
> > ```
> 
> Do you mean that there isn't actually a real scenario that would trigger the bug caused here?

It could be if #187 was merged.

**Comment by Gobot1234** [comment]
I'm gonna merge this with #187

**Pull request closed without merging**
