### PR TITLE
Fix compilation of fields named 'bytes'

### PR DESCRIPTION
**Pull request by SpencerSharkey**
If you have a bytes field named "bytes", a recursion error occurs when importing the compiled stubs.

### CODE REVIEW

**Comment by Gobot1234** [comment]
Why is `bytes` a special case, should it not happen for all builtin types?

**Comment by nat-n** [comment]
@SpencerSharkey thanks for doing this. 

The solution looks reasonable, however as @Gobot1234 it may be that you've scratched the surface of a larger issue here.

That said it's not immediately obvious to me exactly why this error is happening. I don't have a lot of time to look into this now, but if you could post an (abridged) stack trace of the recursion error then that would help :)

Also it would be good to have a regression test for this, would you be willing to add an example to the test suite following the pattern described here https://github.com/danielgtaylor/python-betterproto/tree/master/tests ?

**Comment by Gobot1234** [comment]
I can't reproduce this
```proto
syntax = "proto3";

message Test {
    bytes bytes = 1;  // or string bytes = 1;
}
```both compile fine for me. Can you show an example where this doesn't work?

**Comment by giantryansaul** [comment]
Commented on the related issue #210, I'm seeing a recursive issue from a definition we have that uses `bytes`. I tested out this PR locally and it fixed my runtime issue.

**Comment by nat-n** [comment]
@SpencerSharkey Thanks again for your contributiong.

I'm closing in favour of #226 because I made some tweaks to extend the fix and enable a test that has already been written to cover it, but didn't have write access to push to the fork (there's a checkbox to allow this when creating the PR).

**Pull request closed without merging**
