### PR TITLE
Replace pkg_resources with importlib

### PR DESCRIPTION
**Pull request by pi-slh**
* Updates _version.py with importlib.metadata
* Updates pyproject.toml with importlib-metadata for python 3.7

Addresses #461

### CODE REVIEW

**Comment by c3b5aw** [comment]
Bump, `pkg_resources` is deprecated Python>=3.9 (Ref: https://setuptools.pypa.io/en/latest/pkg_resources.html)
image

**Review by MicaelJarniac — APPROVED** [review]

**Review by Gobot1234 — APPROVED** [review]
Thank you

**Comment by MicaelJarniac** [comment]
When will this be included in a release or pre-release?

**Comment by Gobot1234** [comment]
I can't make any promises but I'm free most of next week so if any maintainers are free I'll be able to hopefully get out b6

**Pull request merged**
