### PR TITLE
Define __all__

### PR DESCRIPTION
**Pull request by AdrienVannson**
## Summary

Define `__all__` in the generated files, as suggested by https://github.com/danielgtaylor/python-betterproto/issues/486

## Checklist

- [X] If code changes were made then they have been tested.
- [X] This PR fixes an issue.
- [X] This PR adds something new (e.g. new method or parameters).

### CODE REVIEW

**Comment by Gobot1234** [comment]
Please move this to the end of the file, because honestly it's not something I want to see

**Comment by Gobot1234** [comment]
Also please can you change this to a tuple not a list

**Comment by AdrienVannson** [comment]
It is defined at the top of the file on purpose, as suggested by PEP-8: https://peps.python.org/pep-0008/#module-level-dunder-names

**Comment by Gobot1234** [comment]
Please can you add a test that this exists and avoids importing dataclasses etc?

**Comment by Gobot1234** [comment]
> It is defined at the top of the file on purpose, as suggested by PEP-8: [peps.python.org/pep-0008#module-level-dunder-names](https://peps.python.org/pep-0008/#module-level-dunder-names)

I have never seen it go before module imports hmm.

**Review by cetanu — APPROVED** [review]
If the python docs say it should go before imports, then okay.

**Comment by AdrienVannson** [comment]
> Please can you add a test that this exists and avoids importing dataclasses etc?

I added a test that check that `__all__` is correctly defined. However, I'm not sure what you mean by importing dataclasses

**Review by Gobot1234 — APPROVED** [review]

**Pull request merged**
