### PR TITLE
Add support for streaming delimited messages

### PR DESCRIPTION
**Pull request by JoshuaLeivers**
This allows developers to easily dump and load multiple messages
from a stream in a way that is compatible with official
protobuf implementations (such as Java's
MessageLite#writeDelimitedTo(...)).

This also adds compatibility tests between the official Java Protobuf
implementation and the new and existing streaming functions in
Betterproto. These tests stream data such as messages to output
files, have a Java binary read them and then write them back using
the protobuf-java functions, and then read them back in on the
Python side to check that the returned data is as expected. This
checks that the official Java implementation (and so any other
matching implementations) can properly parse outputs from
Betterproto, and vice-versa, ensuring compatibility in these
functions between the two.

The Java binary is built on the fly as part of a Pytest fixture, and
these tests are skipped if any necessary tools (i.e. Java or Maven)
are missing from the host machine, or if the build fails (e.g. due
to an incompatible Java version).

### CODE REVIEW

**Comment by JoshuaLeivers** [comment]
Sorry about the force-pushes, was just quickly fixing up the CI test fails before it could be reviewed properly, will avoid them from now on 🙂

**Comment by JoshuaLeivers** [comment]
This should finish addressing the message streaming part of #482 , would it be possible to get a review for this?

**Comment by JoshuaLeivers** [comment]
Just rebased onto current `master`

**Comment by JoshuaLeivers** [comment]
Had to resign the commits

**Comment by cetanu** [comment]
Looks reasonable to me, thanks for this work

**Review by cetanu — APPROVED** [review]

**Pull request merged**
