### PR TITLE
Update Jinja 2 version

### PR DESCRIPTION
**Pull request by chitalian**
Update jinja version.
see: https://github.com/danielgtaylor/python-betterproto/issues/401

### CODE REVIEW

**Comment by Gobot1234** [comment]
You need to update the poetry.lock.

**Comment by chitalian** [comment]
@Gobot1234 

> You need to update the poetry.lock.

When I try to update it I get
```
For jinja2, a possible solution would be to set the `python` property to ">=3.7,<4.0"
```

Is it okay to change python version min to be 3.7?

**Comment by Gobot1234** [comment]
> @Gobot1234 
> 
> 
> 
> > You need to update the poetry.lock.
> 
> 
> 
> When I try to update it I get
> 
> ```
> 
> For jinja2, a possible solution would be to set the `python` property to ">=3.7,<4.0"
> 
> ```
> 
> 
> 
> Is it okay to change python version min to be 3.7?
> 
> 
> 
> 

As a last resort maybe but can you see if there's a version that still supports 3.6?

**Review by Gobot1234 — APPROVED** [review]

**Comment by Gobot1234** [comment]
Thanks

**Pull request merged**
